version: "3"
services:
  redoc:
    image: redocly/redoc
    volumes:
      - './open-api/openapi.yml:/usr/share/nginx/html/openapi.yml'
    environment:
      SPEC_URL: openapi.yml
    ports:
      - '8100:80'
  redoc-test:
    image: redocly/redoc
    volumes:
      - './open-api/openapi-test.yml:/usr/share/nginx/html/openapi-test.yml'
    environment:
      SPEC_URL: openapi-test.yml
    ports:
      - '8200:80'

networks:
  default:
    name: itblog_network

